import { Text } from '@chakra-ui/react'
import React from 'react'

const CountryCodeDrop = () => {
  return (
    <div style={{textAlign:'left'}}>
        <Text textAlign='left'>Afghanistan 93</Text>
        <Text textAlign='left'>Albania 355</Text>
        <Text textAlign='left'>Algeria 213</Text>
        <Text textAlign='left'>American Samoa 1 684</Text>
        <Text textAlign='left'>Andorra 376</Text>
        <Text textAlign='left'>Angola 244</Text>
        <Text textAlign='left'>Anguilla 1 264</Text>
        <Text textAlign='left'>Antarctica (Australian bases) 672 1</Text>
        <Text textAlign='left'>Antigua and Barbuda 1 268</Text>
        <Text textAlign='left'>Argentina 54</Text>
        <Text textAlign='left'>Armenia 374</Text>
        <Text textAlign='left'>Aruba 297</Text>
        <Text textAlign='left'>Ascension 247</Text>
        <Text textAlign='left'>Australia 61</Text>
        <Text textAlign='left'>Austria 43</Text>
        <Text textAlign='left'>Azerbaijan 994</Text>
        <Text textAlign='left'>Bahamas 1 242</Text>
        <Text textAlign='left'>Bahrain 973</Text>
        <Text textAlign='left'>Bangladesh 880</Text>
        <Text textAlign='left'>Barbados 1 246</Text>
        <Text textAlign='left'>Belarus 375</Text>
        <Text textAlign='left'>Belgium 32</Text>
        <Text textAlign='left'>Belize 501</Text>
        <Text textAlign='left'>Benin 229</Text>
        <Text textAlign='left'>Bermuda 1 441</Text>
        <Text textAlign='left'>Bhutan 975</Text>
        <Text textAlign='left'>Bolivia 591</Text>
        <Text textAlign='left'>Bonaire 599</Text>
        <Text textAlign='left'>Bosnia and Herzegovina 387</Text>
        <Text textAlign='left'>Botswana 267</Text>
        <Text textAlign='left'>Brazil 55</Text>
        <Text textAlign='left'>British Virgin Islands 1 284</Text>
        <Text textAlign='left'>Brunei 673</Text>
        <Text textAlign='left'>Bulgaria 359</Text>
        <Text textAlign='left'>Burkina Faso 226</Text>
        <Text textAlign='left'>Burundi 257</Text>
        <Text textAlign='left'>Cabo Verde 238</Text>
        <Text textAlign='left'>Cambodia 855</Text>
        <Text textAlign='left'>Cameroon 237</Text>
        <Text textAlign='left'>Canada 1</Text>
        <Text textAlign='left'>Cayman Islands 1 345</Text>
        <Text textAlign='left'>Central African Republic 236</Text>
        <Text textAlign='left'>Chad 235</Text>
        <Text textAlign='left'>Chile 56</Text>
        <Text textAlign='left'>China 86</Text>
        <Text textAlign='left'>Colombia 57</Text>
        <Text textAlign='left'>Comoros 269</Text>
        <Text textAlign='left'>Congo, Democratic Republic of the 2</Text>
        <Text textAlign='left'>Congo, Republic of the 242</Text>
        <Text textAlign='left'>Cook Islands 682</Text>
        <Text textAlign='left'>Costa Rica 506</Text>
        <Text textAlign='left'>Cote d'Ivoire 225</Text>
        <Text textAlign='left'>Croatia 385</Text>
        <Text textAlign='left'>Cuba 53</Text>
        <Text textAlign='left'>Curaçao 599</Text>
        <Text textAlign='left'>Cyprus 357</Text>
        <Text textAlign='left'>Czech Republic 420</Text>
        <Text textAlign='left'>Denmark 45</Text>
        <Text textAlign='left'>Diego Garcia 246</Text>
        <Text textAlign='left'>Djibouti 253</Text>
        <Text textAlign='left'>Dominica 1 767</Text>
        <Text textAlign='left'>Dominican Republic 1 809, 1 829, an</Text>
        <Text textAlign='left'>Ecuador 593</Text>
        <Text textAlign='left'>Egypt 20</Text>
        <Text textAlign='left'>El Salvador 503</Text>
        <Text textAlign='left'>Equatorial Guinea 240</Text>
        <Text textAlign='left'>Eritrea 291</Text>
        <Text textAlign='left'>Estonia 372</Text>
        <Text textAlign='left'>Eswatini 268</Text>
        <Text textAlign='left'>Ethiopia 251</Text>
        <Text textAlign='left'>Falkland Islands 500</Text>
        <Text textAlign='left'>Faroe Islands 298</Text>
        <Text textAlign='left'>Fiji 679</Text>
        <Text textAlign='left'>Finland 358</Text>
        <Text textAlign='left'>France 33</Text>
        <Text textAlign='left'>French Guiana 594</Text>
        <Text textAlign='left'>French Polynesia 689</Text>
        <Text textAlign='left'>Gabon 241</Text>
        <Text textAlign='left'>Gambia 220</Text>
        <Text textAlign='left'>Georgia 995</Text>
        <Text textAlign='left'>Germany 49</Text>
        <Text textAlign='left'>Ghana 233</Text>
        <Text textAlign='left'>Gibraltar 350</Text>
        <Text textAlign='left'>Greece 30</Text>
        <Text textAlign='left'>Greenland 299</Text>
        <Text textAlign='left'>Grenada 1 473</Text>
        <Text textAlign='left'>Guadeloupe 590</Text>
        <Text textAlign='left'>Guam 1 671</Text>
        <Text textAlign='left'>Guatemala 502</Text>
        <Text textAlign='left'>Guinea 224</Text>
        <Text textAlign='left'>Guinea-Bissau 245</Text>
        <Text textAlign='left'>Guyana 592</Text>
        <Text textAlign='left'>Haiti 509</Text>
        <Text textAlign='left'>Honduras 504</Text>
        <Text textAlign='left'>Hong Kong 852</Text>
        <Text textAlign='left'>Hungary 36</Text>
        <Text textAlign='left'>Iceland 354</Text>
        <Text textAlign='left'>India 91</Text>
        <Text textAlign='left'>Indonesia 62</Text>
        <Text textAlign='left'>Iran 98</Text>
        <Text textAlign='left'>Iraq 964</Text>
        <Text textAlign='left'>Ireland (Eire) 353</Text>
        <Text textAlign='left'>Israel 972</Text>
        <Text textAlign='left'>Italy 39</Text>
        <Text textAlign='left'>Jamaica 1 658, 1 876</Text>
        <Text textAlign='left'>Japan 81</Text>
        <Text textAlign='left'>Jordan 962</Text>
        <Text textAlign='left'>Kazakhstan 7</Text>
        <Text textAlign='left'>Kenya 254</Text>
        <Text textAlign='left'>Kiribati 686</Text>
        <Text textAlign='left'>Kosovo 383</Text>
        <Text textAlign='left'>Kuwait 965</Text>
        <Text textAlign='left'>Kyrgyzstan 996</Text>
        <Text textAlign='left'>Laos 856</Text>
        <Text textAlign='left'>Latvia 371</Text>
        <Text textAlign='left'>Lebanon 961</Text>
        <Text textAlign='left'>Lesotho 266</Text>
        <Text textAlign='left'>Liberia 231</Text>
        <Text textAlign='left'>Libya 218</Text>
        <Text textAlign='left'>Liechtenstein 423</Text>
        <Text textAlign='left'>Lithuania 370</Text>
        <Text textAlign='left'>Luxembourg 352</Text>
        <Text textAlign='left'>Macau 853</Text>
        <Text textAlign='left'>Madagascar 261</Text>
        <Text textAlign='left'>Malawi 265</Text>
        <Text textAlign='left'>Malaysia 60</Text>
        <Text textAlign='left'>Maldives 960</Text>
        <Text textAlign='left'>Mali 223</Text>
        <Text textAlign='left'>Malta 356</Text>
        <Text textAlign='left'>Marshall Islands 692</Text>
        <Text textAlign='left'>Martinique 596</Text>
        <Text textAlign='left'>Mauritania 222</Text>
        <Text textAlign='left'>Mauritius 230</Text>
        <Text textAlign='left'>Mayotte 262</Text>
        <Text textAlign='left'>Mexico 52</Text>
        <Text textAlign='left'>Micronesia, Federated States of 691</Text>
        <Text textAlign='left'>Moldova 373</Text>
        <Text textAlign='left'>Monaco 377</Text>
        <Text textAlign='left'>Mongolia 976</Text>
        <Text textAlign='left'>Montenegro 382</Text>
        <Text textAlign='left'>Montserrat 1 664</Text>
        <Text textAlign='left'>Morocco 212</Text>
        <Text textAlign='left'>Mozambique 258</Text>
        <Text textAlign='left'>Myanmar 95</Text>
        <Text textAlign='left'>Namibia 264</Text>
        <Text textAlign='left'>Nauru 674</Text>
        <Text textAlign='left'>Nepal 977</Text>
        <Text textAlign='left'>Netherlands 31</Text>
        <Text textAlign='left'>New Caledonia 687</Text>
        <Text textAlign='left'>New Zealand 64</Text>
        <Text textAlign='left'>Nicaragua 505</Text>
        <Text textAlign='left'>Niger 227</Text>
        <Text textAlign='left'>Nigeria 234</Text>
        <Text textAlign='left'>Niue 683</Text>
        <Text textAlign='left'>Norfolk Island 672 3</Text>
        <Text textAlign='left'>North Korea 850</Text>
        <Text textAlign='left'>North Macedonia 389</Text>
        <Text textAlign='left'>Northern Mariana Islands 1 670</Text>
        <Text textAlign='left'>Norway 47</Text>
        <Text textAlign='left'>Oman 968</Text>
        <Text textAlign='left'>Pakistan 92</Text>
        <Text textAlign='left'>Palau 680</Text>
        <Text textAlign='left'>Palestine 970</Text>
        <Text textAlign='left'>Panama 507</Text>
        <Text textAlign='left'>Papua New Guinea 675</Text>
        <Text textAlign='left'>Paraguay 595</Text>
        <Text textAlign='left'>Peru 51</Text>
        <Text textAlign='left'>Philippines 63</Text>
        <Text textAlign='left'>Poland 48</Text>
        <Text textAlign='left'>Portugal 351</Text>
        <Text textAlign='left'>Puerto Rico 1 787 and 1 939</Text>
        <Text textAlign='left'>Qatar 974</Text>
        <Text textAlign='left'>Reunion 262</Text>
        <Text textAlign='left'>Romania 40</Text>
        <Text textAlign='left'>Russia 7</Text>
        <Text textAlign='left'>Rwanda 250</Text>
        <Text textAlign='left'>Saba 599</Text>
        <Text textAlign='left'>Saint-Barthelemy 590</Text>
        <Text textAlign='left'>Saint Helena 290</Text>
        <Text textAlign='left'>Saint Kitts and Nevis 1 869</Text>
        <Text textAlign='left'>Saint Lucia 1 758</Text>
        <Text textAlign='left'>Saint Martin (French side) 590</Text>
        <Text textAlign='left'>Saint Pierre and Miquelon 508</Text>
        <Text textAlign='left'>Saint Vincent and the Grenadines 1 </Text>
        <Text textAlign='left'>Samoa 685</Text>
        <Text textAlign='left'>San Marino 378</Text>
        <Text textAlign='left'>Sao Tome and Principe 239</Text>
        <Text textAlign='left'>Saudi Arabia 966</Text>
        <Text textAlign='left'>Senegal 221</Text>
        <Text textAlign='left'>Serbia 381</Text>
        <Text textAlign='left'>Seychelles 248</Text>
        <Text textAlign='left'>Sierra Leone 232</Text>
        <Text textAlign='left'>Singapore 65</Text>
        <Text textAlign='left'>Sint Eustatius 599</Text>
        <Text textAlign='left'>Sint Maarten (Dutch side) 1 721</Text>
        <Text textAlign='left'>Slovakia 421</Text>
        <Text textAlign='left'>Slovenia 386</Text>
        <Text textAlign='left'>Solomon Islands 677</Text>
        <Text textAlign='left'>Somalia 252</Text>
        <Text textAlign='left'>South Africa 27</Text>
        <Text textAlign='left'>South Korea 82</Text>
        <Text textAlign='left'>South Sudan 211</Text>
        <Text textAlign='left'>Spain 34</Text>
        <Text textAlign='left'>Sri Lanka 94</Text>
        <Text textAlign='left'>Sudan 249</Text>
        <Text textAlign='left'>Suriname 597</Text>
        <Text textAlign='left'>Sweden 46</Text>
        <Text textAlign='left'>Switzerland 41</Text>
        <Text textAlign='left'>Syria 963</Text>
        <Text textAlign='left'>Taiwan 886</Text>
        <Text textAlign='left'>Tajikistan 992</Text>
        <Text textAlign='left'>Tanzania 255</Text>
        <Text textAlign='left'>Thailand 66</Text>
        <Text textAlign='left'>Timor-Leste 670</Text>
        <Text textAlign='left'>Togo 228</Text>
        <Text textAlign='left'>Tokelau 690</Text>
        <Text textAlign='left'>Tonga 676</Text>
        <Text textAlign='left'>Trinidad and Tobago 1 868</Text>
        <Text textAlign='left'>Tristan da Cunha 290</Text>
        <Text textAlign='left'>Tunisia 216</Text>
        <Text textAlign='left'>Turkey 90</Text>
        <Text textAlign='left'>Turkmenistan 993</Text>
        <Text textAlign='left'>Turks and Caicos Islands 1 649</Text>
        <Text textAlign='left'>Tuvalu 688</Text>
        <Text textAlign='left'>Uganda 256</Text>
        <Text textAlign='left'>Ukraine 380</Text>
        <Text textAlign='left'>United Arab Emirates 971</Text>
        <Text textAlign='left'>United Kingdom 44</Text>
        <Text textAlign='left'>United States of America 1</Text>
        <Text textAlign='left'>Uruguay 598</Text>
        <Text textAlign='left'>Uzbekistan 998</Text>
        <Text textAlign='left'>Vanuatu 678</Text>
        <Text textAlign='left'>Vatican City State 39</Text>
        <Text textAlign='left'>Venezuela 58</Text>
        <Text textAlign='left'>Vietnam 84</Text>
        <Text textAlign='left'>U.S. Virgin Islands 1 340</Text>
        <Text textAlign='left'>Wallis and Futuna 681</Text>
        <Text textAlign='left'>Yemen 967</Text>
        <Text textAlign='left'>Zambia 260</Text>
        <Text textAlign='left'>Zimbabwe 263</Text>
    </div>
  )
}

export default CountryCodeDrop